In [31]:
import json
import pandas as pd

with open("../data/jobs_master.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)

print(df.shape)
df.head()

(71, 16)

,source,job_title,company,city,location,employment_type,salary,skills,experience_level,apply_link,posted_at,description,combined_text,extracted_skills,listed_skills,final_skills
0,Jooble,"Senior Mechanical Quality Assurance Engineer, KSA",elsewedy electric power systems projects,N/A,Saudi Arabia,N/A,,Quality Assurance,Senior,https://sa.jooble.org/jdp/6257477343626522564,2026-09-11T17:07:27.2500000,&nbsp;...elsewedy electric power systems proje...,"Senior Mechanical Quality Assurance Engineer, ...",[Quality Assurance],[],Quality Assurance
1,Jooble,Forward Deployed Engineer - Software Engineer ...,elevenlabs,N/A,Saudi Arabia,N/A,,Python,N/A,https://sa.jooble.org/jdp/7464896514165086194,2026-09-11T11:55:39.4447750+00:00,&nbsp;...beneath you. \r\n AI first: We use A...,Forward Deployed Engineer - Software Engineer ...,"[Python, Software Development, AI]",[],"Python, Software Development, AI"
2,Jooble,Quality Engineer,Greenfix Property Care,N/A,Saudi Arabia,N/A,,N/A,Junior,https://sa.jooble.org/jdp/-2119268642614167659,2025-12-07T03:15:41.8570000,Overview We are seeking a <b>Software </b>Te...,Quality Engineer Overview We are seeking a <...,[Automation Testing],[],Automation Testing
3,Jooble,Deal Quality Specialist,Saudi Aramco (ASC),N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/3549816380665494847,2026-01-12T00:00:00.0000000,"&nbsp;...companies in the world, as well as am...",Deal Quality Specialist &nbsp;...companies in ...,[],[],N/A
4,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,N/A,Saudi Arabia,N/A,,N/A,Senior,https://sa.jooble.org/jdp/-1483870771996984571,2026-08-07T11:23:21.9900000,&nbsp;...the world forward. Built on Lucid’s p...,Incoming Quality Sr. Supervisor &nbsp;...the w...,[],[],N/A

In [32]:
print(df.columns.tolist())
print(df.dtypes)
df.isnull().sum()

['source', 'job_title', 'company', 'city', 'location', 'employment_type', 'salary', 'skills', 'experience_level', 'apply_link', 'posted_at', 'description', 'combined_text', 'extracted_skills', 'listed_skills', 'final_skills']
source                 str
job_title              str
company                str
city                   str
location               str
employment_type        str
salary                 str
skills                 str
experience_level       str
apply_link             str
posted_at              str
description            str
combined_text          str
extracted_skills    object
listed_skills       object
final_skills           str
dtype: object

source               0
job_title            0
company              0
city                 0
location             0
employment_type      0
salary               0
skills               0
experience_level     0
apply_link           0
posted_at           15
description         14
combined_text       41
extracted_skills    41
listed_skills       41
final_skills        41
dtype: int64

In [33]:
import json
import pandas as pd

with open("../data/jobs_master.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)

print(df.shape)
df.head()

(71, 16)

,source,job_title,company,city,location,employment_type,salary,skills,experience_level,apply_link,posted_at,description,combined_text,extracted_skills,listed_skills,final_skills
0,Jooble,"Senior Mechanical Quality Assurance Engineer, KSA",elsewedy electric power systems projects,N/A,Saudi Arabia,N/A,,Quality Assurance,Senior,https://sa.jooble.org/jdp/6257477343626522564,2026-09-11T17:07:27.2500000,&nbsp;...elsewedy electric power systems proje...,"Senior Mechanical Quality Assurance Engineer, ...",[Quality Assurance],[],Quality Assurance
1,Jooble,Forward Deployed Engineer - Software Engineer ...,elevenlabs,N/A,Saudi Arabia,N/A,,Python,N/A,https://sa.jooble.org/jdp/7464896514165086194,2026-09-11T11:55:39.4447750+00:00,&nbsp;...beneath you. \r\n AI first: We use A...,Forward Deployed Engineer - Software Engineer ...,"[Python, Software Development, AI]",[],"Python, Software Development, AI"
2,Jooble,Quality Engineer,Greenfix Property Care,N/A,Saudi Arabia,N/A,,N/A,Junior,https://sa.jooble.org/jdp/-2119268642614167659,2025-12-07T03:15:41.8570000,Overview We are seeking a <b>Software </b>Te...,Quality Engineer Overview We are seeking a <...,[Automation Testing],[],Automation Testing
3,Jooble,Deal Quality Specialist,Saudi Aramco (ASC),N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/3549816380665494847,2026-01-12T00:00:00.0000000,"&nbsp;...companies in the world, as well as am...",Deal Quality Specialist &nbsp;...companies in ...,[],[],N/A
4,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,N/A,Saudi Arabia,N/A,,N/A,Senior,https://sa.jooble.org/jdp/-1483870771996984571,2026-08-07T11:23:21.9900000,&nbsp;...the world forward. Built on Lucid’s p...,Incoming Quality Sr. Supervisor &nbsp;...the w...,[],[],N/A

In [34]:
import json
import pandas as pd

with open("../data/jobs_master.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)

print(df.shape)
df.head(10)

(71, 16)

,source,job_title,company,city,location,employment_type,salary,skills,experience_level,apply_link,posted_at,description,combined_text,extracted_skills,listed_skills,final_skills
0,Jooble,"Senior Mechanical Quality Assurance Engineer, KSA",elsewedy electric power systems projects,N/A,Saudi Arabia,N/A,,Quality Assurance,Senior,https://sa.jooble.org/jdp/6257477343626522564,2026-09-11T17:07:27.2500000,&nbsp;...elsewedy electric power systems proje...,"Senior Mechanical Quality Assurance Engineer, ...",[Quality Assurance],[],Quality Assurance
1,Jooble,Forward Deployed Engineer - Software Engineer ...,elevenlabs,N/A,Saudi Arabia,N/A,,Python,N/A,https://sa.jooble.org/jdp/7464896514165086194,2026-09-11T11:55:39.4447750+00:00,&nbsp;...beneath you. \r\n AI first: We use A...,Forward Deployed Engineer - Software Engineer ...,"[Python, Software Development, AI]",[],"Python, Software Development, AI"
2,Jooble,Quality Engineer,Greenfix Property Care,N/A,Saudi Arabia,N/A,,N/A,Junior,https://sa.jooble.org/jdp/-2119268642614167659,2025-12-07T03:15:41.8570000,Overview We are seeking a <b>Software </b>Te...,Quality Engineer Overview We are seeking a <...,[Automation Testing],[],Automation Testing
3,Jooble,Deal Quality Specialist,Saudi Aramco (ASC),N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/3549816380665494847,2026-01-12T00:00:00.0000000,"&nbsp;...companies in the world, as well as am...",Deal Quality Specialist &nbsp;...companies in ...,[],[],N/A
4,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,N/A,Saudi Arabia,N/A,,N/A,Senior,https://sa.jooble.org/jdp/-1483870771996984571,2026-08-07T11:23:21.9900000,&nbsp;...the world forward. Built on Lucid’s p...,Incoming Quality Sr. Supervisor &nbsp;...the w...,[],[],N/A
5,Jooble,Quality Engineer,Seerah,N/A,Saudi Arabia,N/A,,QA,N/A,https://sa.jooble.org/jdp/8180032376905932691,2026-09-08T00:00:00.0000000,&nbsp;...Job Description: \r\n Seerah is seeki...,Quality Engineer &nbsp;...Job Description: \r\...,"[Quality Assurance, Quality Control, Complianc...",[],"Quality Assurance, Quality Control, Compliance..."
6,Jooble,Quality Manager,Ennismore,N/A,Saudi Arabia,N/A,,N/A,Manager,https://sa.jooble.org/jdp/-4060408321821370081,2026-09-10T00:00:00.0000000,&nbsp;...you to help bring this vision to life...,Quality Manager &nbsp;...you to help bring thi...,"[Quality Assurance, Compliance]",[],"Quality Assurance, Compliance"
7,Jooble,PMO Operations & Quality Lead,Hill Intl.,N/A,Saudi Arabia,N/A,,Quality Assurance,Lead,https://sa.jooble.org/jdp/6732476449698777483,2026-09-11T00:00:00.0000000,&nbsp;...Manager (E1) to lead PMO best practic...,PMO Operations & Quality Lead &nbsp;...Manager...,"[Monitoring, Quality Assurance]",[],"Quality Assurance, Monitoring"
8,Jooble,Software Engineer,PrimeGate Company,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/-2685678295966072847,2026-09-10T00:00:00.0000000,&nbsp;...About the Role \r\n We are looking fo...,Software Engineer &nbsp;...About the Role \r\n...,[Web Applications],[],Web Applications
9,Jooble,Software Developer & Database Architects,Euro Group,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/-1459070999588527884,2026-09-07T00:00:00.0000000,&nbsp;...<b>Software </b>Developer & Database ...,Software Developer & Database Architects &nbsp...,[Database],[],Database

In [35]:
print(df.columns.tolist())
print(df.dtypes)
df.isnull().sum()

['source', 'job_title', 'company', 'city', 'location', 'employment_type', 'salary', 'skills', 'experience_level', 'apply_link', 'posted_at', 'description', 'combined_text', 'extracted_skills', 'listed_skills', 'final_skills']
source                 str
job_title              str
company                str
city                   str
location               str
employment_type        str
salary                 str
skills                 str
experience_level       str
apply_link             str
posted_at              str
description            str
combined_text          str
extracted_skills    object
listed_skills       object
final_skills           str
dtype: object

source               0
job_title            0
company              0
city                 0
location             0
employment_type      0
salary               0
skills               0
experience_level     0
apply_link           0
posted_at           15
description         14
combined_text       41
extracted_skills    41
listed_skills       41
final_skills        41
dtype: int64

In [36]:
import pandas as pd
import re
import html

In [37]:
# The DataFrame (df) was created in the previous data processing step

print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

df.head()

Number of rows: 71
Number of columns: 16

,source,job_title,company,city,location,employment_type,salary,skills,experience_level,apply_link,posted_at,description,combined_text,extracted_skills,listed_skills,final_skills
0,Jooble,"Senior Mechanical Quality Assurance Engineer, KSA",elsewedy electric power systems projects,N/A,Saudi Arabia,N/A,,Quality Assurance,Senior,https://sa.jooble.org/jdp/6257477343626522564,2026-09-11T17:07:27.2500000,&nbsp;...elsewedy electric power systems proje...,"Senior Mechanical Quality Assurance Engineer, ...",[Quality Assurance],[],Quality Assurance
1,Jooble,Forward Deployed Engineer - Software Engineer ...,elevenlabs,N/A,Saudi Arabia,N/A,,Python,N/A,https://sa.jooble.org/jdp/7464896514165086194,2026-09-11T11:55:39.4447750+00:00,&nbsp;...beneath you. \r\n AI first: We use A...,Forward Deployed Engineer - Software Engineer ...,"[Python, Software Development, AI]",[],"Python, Software Development, AI"
2,Jooble,Quality Engineer,Greenfix Property Care,N/A,Saudi Arabia,N/A,,N/A,Junior,https://sa.jooble.org/jdp/-2119268642614167659,2025-12-07T03:15:41.8570000,Overview We are seeking a <b>Software </b>Te...,Quality Engineer Overview We are seeking a <...,[Automation Testing],[],Automation Testing
3,Jooble,Deal Quality Specialist,Saudi Aramco (ASC),N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/3549816380665494847,2026-01-12T00:00:00.0000000,"&nbsp;...companies in the world, as well as am...",Deal Quality Specialist &nbsp;...companies in ...,[],[],N/A
4,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,N/A,Saudi Arabia,N/A,,N/A,Senior,https://sa.jooble.org/jdp/-1483870771996984571,2026-08-07T11:23:21.9900000,&nbsp;...the world forward. Built on Lucid’s p...,Incoming Quality Sr. Supervisor &nbsp;...the w...,[],[],N/A

In [38]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types before transformation:")
print(df.dtypes)

print("\nMissing values before transformation:")
print(df.isna().sum())

Shape: (71, 16)

Columns:
['source', 'job_title', 'company', 'city', 'location', 'employment_type', 'salary', 'skills', 'experience_level', 'apply_link', 'posted_at', 'description', 'combined_text', 'extracted_skills', 'listed_skills', 'final_skills']

Data types before transformation:
source                 str
job_title              str
company                str
city                   str
location               str
employment_type        str
salary                 str
skills                 str
experience_level       str
apply_link             str
posted_at              str
description            str
combined_text          str
extracted_skills    object
listed_skills       object
final_skills           str
dtype: object

Missing values before transformation:
source               0
job_title            0
company              0
city                 0
location             0
employment_type      0
salary               0
skills               0
experience_level     0
apply_link           0
posted_at           15
description         14
combined_text       41
extracted_skills    41
listed_skills       41
final_skills        41
dtype: int64

In [39]:
rows_before = len(df)

df = df.drop_duplicates(
    subset=["job_title", "company", "location"],
    keep="first"
).copy()

rows_after = len(df)

print("Rows before:", rows_before)
print("Rows after:", rows_after)
print("Duplicates removed:", rows_before - rows_after)

Rows before: 71
Rows after: 70
Duplicates removed: 1

In [40]:
missing_values = [
    "N/A",
    "NA",
    "None",
    "NULL",
    ""
]

df = df.replace(missing_values, pd.NA)

print(df.isna().sum())

source               0
job_title            0
company              0
city                55
location             0
employment_type     45
salary              70
skills              49
experience_level    50
apply_link           0
posted_at           15
description         14
combined_text       40
extracted_skills    40
listed_skills       40
final_skills        42
dtype: int64

In [41]:
text_columns = [
    "source",
    "job_title",
    "company",
    "city",
    "location",
    "employment_type",
    "experience_level"
]

for col in text_columns:
    if col in df.columns:
        df[col] = (
            df[col]
            .astype("string")
            .str.strip()
            .str.replace(r"\s+", " ", regex=True)
        )

df[text_columns].head()

,source,job_title,company,city,location,employment_type,experience_level
0,Jooble,"Senior Mechanical Quality Assurance Engineer, KSA",elsewedy electric power systems projects,<NA>,Saudi Arabia,<NA>,Senior
1,Jooble,Forward Deployed Engineer - Software Engineer ...,elevenlabs,<NA>,Saudi Arabia,<NA>,<NA>
2,Jooble,Quality Engineer,Greenfix Property Care,<NA>,Saudi Arabia,<NA>,Junior
3,Jooble,Deal Quality Specialist,Saudi Aramco (ASC),<NA>,Saudi Arabia,<NA>,<NA>
4,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,<NA>,Saudi Arabia,<NA>,Senior

In [42]:
def clean_description(value):

    if pd.isna(value):
        return pd.NA

    text = html.unescape(str(value))

    # Remove HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text if text else pd.NA


df["description"] = df["description"].apply(clean_description)

df[["description"]].head()

                                         description
0  ...elsewedy electric power systems projects se...
1  ...beneath you. AI first: We use AI to move fa...
2  Overview We are seeking a Software Tester with...
3  ...companies in the world, as well as amongst ...
4  ...the world forward. Built on Lucid’s proprie...

In [43]:
df["posted_at"] = pd.to_datetime(
    df["posted_at"],
    format="mixed",
    errors="coerce",
    utc=True
)

print("posted_at type:")
print(df["posted_at"].dtype)

df[["job_title", "posted_at"]].head()

posted_at type:
datetime64[ns, UTC]

,job_title,posted_at
0,"Senior Mechanical Quality Assurance Engineer, KSA",2026-09-11 17:07:27.250000+00:00
1,Forward Deployed Engineer - Software Engineer ...,2026-09-11 11:55:39.444775+00:00
2,Quality Engineer,2025-12-07 03:15:41.857000+00:00
3,Deal Quality Specialist,2026-01-12 00:00:00+00:00
4,Incoming Quality Sr. Supervisor,2026-08-07 11:23:21.990000+00:00

In [44]:
df["salary"] = pd.to_numeric(
    df["salary"],
    errors="coerce"
).astype("Float64")

print("Salary type:", df["salary"].dtype)
print("Available salaries:", df["salary"].notna().sum())
print("Missing salaries:", df["salary"].isna().sum())

Salary type: Float64
Available salaries: 0
Missing salaries: 70

In [45]:
valid_levels = [
    "Intern",
    "Junior",
    "Mid Level",
    "Senior",
    "Senior Lead",
    "Lead",
    "Manager",
    "Director",
    "Principal"
]

df["experience_level"] = df["experience_level"].where(
    df["experience_level"].isin(valid_levels),
    pd.NA
)

print(df["experience_level"].value_counts(dropna=False))

experience_level
<NA>           50
Senior          8
Lead            6
Manager         2
Junior          1
Principal       1
Mid Level       1
Senior Lead     1
Name: count, dtype: Int64

In [46]:
remote_text = (
    df["job_title"].fillna("") + " " +
    df["description"].fillna("")
).str.lower()

df["is_remote"] = (
    remote_text
    .str.contains(r"\bremote\b", regex=True)
    .astype("boolean")
)

print(df["is_remote"].value_counts(dropna=False))

df[
    ["job_title", "is_remote"]
].head(10)

is_remote
False    66
True      4
Name: count, dtype: Int64

                                           job_title  is_remote
0  Senior Mechanical Quality Assurance Engineer, KSA      False
1  Forward Deployed Engineer - Software Engineer ...      False
2                                   Quality Engineer      False
3                            Deal Quality Specialist      False
4                    Incoming Quality Sr. Supervisor      False
5                                   Quality Engineer      False
6                                    Quality Manager      False
7                      PMO Operations & Quality Lead      False
8                                  Software Engineer      False
9           Software Developer & Database Architects      False

In [47]:
df["has_salary"] = (
    df["salary"]
    .notna()
    .astype("boolean")
)

print(df["has_salary"].value_counts())

has_salary
False    70
Name: count, dtype: Int64

In [48]:
df["posted_date"] = df["posted_at"].dt.date

df["posted_year"] = (
    df["posted_at"]
    .dt.year
    .astype("Int64")
)

df["posted_month"] = (
    df["posted_at"]
    .dt.month
    .astype("Int64")
)

df["posted_day"] = (
    df["posted_at"]
    .dt.day
    .astype("Int64")
)

df[
    [
        "posted_at",
        "posted_date",
        "posted_year",
        "posted_month",
        "posted_day"
    ]
].head()

,posted_at,posted_date,posted_year,posted_month,posted_day
0,2026-09-11 17:07:27.250000+00:00,2026-09-11,2026,9,11
1,2026-09-11 11:55:39.444775+00:00,2026-09-11,2026,9,11
2,2025-12-07 03:15:41.857000+00:00,2025-12-07,2025,12,7
3,2026-01-12 00:00:00+00:00,2026-01-12,2026,1,12
4,2026-08-07 11:23:21.990000+00:00,2026-08-07,2026,8,7

In [49]:
print("===== TRANSFORMATION SUMMARY =====")

print("\nFinal number of rows:")
print(len(df))

print("\nFinal data types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isna().sum())

print("\nExperience levels:")
print(df["experience_level"].value_counts(dropna=False))

print("\nRemote jobs:")
print(df["is_remote"].value_counts(dropna=False))

print("\nJobs with salary:")
print(df["has_salary"].value_counts(dropna=False))

===== TRANSFORMATION SUMMARY =====

Final number of rows:
70

Final data types:
source                           string
job_title                        string
company                          string
city                             string
location                         string
employment_type                  string
salary                          Float64
skills                              str
experience_level                 string
apply_link                          str
posted_at           datetime64[ns, UTC]
description                         str
combined_text                       str
extracted_skills                 object
listed_skills                    object
final_skills                        str
is_remote                       boolean
has_salary                      boolean
posted_date                      object
posted_year                       Int64
posted_month                      Int64
posted_day                        Int64
dtype: object

Missing values:
source               0
job_title            0
company              0
city                55
location             0
employment_type     45
salary              70
skills              49
experience_level    50
apply_link           0
posted_at           15
description         14
combined_text       40
extracted_skills    40
listed_skills       40
final_skills        42
is_remote            0
has_salary           0
posted_date         15
posted_year         15
posted_month        15
posted_day          15
dtype: int64

Experience levels:
experience_level
<NA>           50
Senior          8
Lead            6
Manager         2
Junior          1
Principal       1
Mid Level       1
Senior Lead     1
Name: count, dtype: Int64

Remote jobs:
is_remote
False    66
True      4
Name: count, dtype: Int64

Jobs with salary:
has_salary
False    70
Name: count, dtype: Int64

In [50]:
preview_columns = [
    "source",
    "job_title",
    "company",
    "city",
    "location",
    "employment_type",
    "salary",
    "experience_level",
    "is_remote",
    "has_salary",
    "posted_at",
    "posted_year",
    "posted_month"
]

df[preview_columns].head(10)

,source,job_title,company,city,location,employment_type,salary,experience_level,is_remote,has_salary,posted_at,posted_year,posted_month
0,Jooble,"Senior Mechanical Quality Assurance Engineer, KSA",elsewedy electric power systems projects,<NA>,Saudi Arabia,<NA>,<NA>,Senior,False,False,2026-09-11 17:07:27.250000+00:00,2026,9
1,Jooble,Forward Deployed Engineer - Software Engineer ...,elevenlabs,<NA>,Saudi Arabia,<NA>,<NA>,<NA>,False,False,2026-09-11 11:55:39.444775+00:00,2026,9
2,Jooble,Quality Engineer,Greenfix Property Care,<NA>,Saudi Arabia,<NA>,<NA>,Junior,False,False,2025-12-07 03:15:41.857000+00:00,2025,12
3,Jooble,Deal Quality Specialist,Saudi Aramco (ASC),<NA>,Saudi Arabia,<NA>,<NA>,<NA>,False,False,2026-01-12 00:00:00+00:00,2026,1
4,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,<NA>,Saudi Arabia,<NA>,<NA>,Senior,False,False,2026-08-07 11:23:21.990000+00:00,2026,8
5,Jooble,Quality Engineer,Seerah,<NA>,Saudi Arabia,<NA>,<NA>,<NA>,False,False,2026-09-08 00:00:00+00:00,2026,9
6,Jooble,Quality Manager,Ennismore,<NA>,Saudi Arabia,<NA>,<NA>,Manager,False,False,2026-09-10 00:00:00+00:00,2026,9
7,Jooble,PMO Operations & Quality Lead,Hill Intl.,<NA>,Saudi Arabia,<NA>,<NA>,Lead,False,False,2026-09-11 00:00:00+00:00,2026,9
8,Jooble,Software Engineer,PrimeGate Company,<NA>,Saudi Arabia,<NA>,<NA>,<NA>,False,False,2026-09-10 00:00:00+00:00,2026,9
9,Jooble,Software Developer & Database Architects,Euro Group,<NA>,Saudi Arabia,<NA>,<NA>,<NA>,False,False,2026-09-07 00:00:00+00:00,2026,9

In [51]:
saudi_cities = [
    "Riyadh",
    "Jeddah",
    "Makkah",
    "Mecca",
    "Madinah",
    "Medina",
    "Dammam",
    "Khobar",
    "Al Khobar",
    "Dhahran",
    "Taif",
    "Tabuk",
    "Abha",
    "Jubail",
    "Yanbu",
    "Najran",
    "Jizan",
    "Buraidah",
    "Hafar Al-Batin"
]


def recover_city(row):

    # Keep existing city
    if pd.notna(row["city"]):
        return row["city"]

    text = " ".join([
        str(row.get("location", "")),
        str(row.get("job_title", "")),
        str(row.get("description", ""))
    ])

    for city in saudi_cities:
        if re.search(
            r"(?<!\w)" + re.escape(city) + r"(?!\w)",
            text,
            re.IGNORECASE
        ):
            return city

    return pd.NA


missing_before = df["city"].isna().sum()

df["city"] = df.apply(recover_city, axis=1)

missing_after = df["city"].isna().sum()

print("Missing cities before:", missing_before)
print("Missing cities after:", missing_after)
print("Cities recovered:", missing_before - missing_after)

print("\nCity distribution:")
print(df["city"].value_counts(dropna=False))

Missing cities before: 55
Missing cities after: 54
Cities recovered: 1

City distribution:
city
NaN               54
Riyadh            11
Hafar Al-Batin     1
Al Khobar          1
Abha               1
Jeddah             1
Makkah             1
Name: count, dtype: int64

In [52]:
def clean_company(company):
    if pd.isna(company):
        return pd.NA

    company = re.sub(r"\s+", " ", str(company)).strip()

    # Only fix names that are completely lowercase
    if company.islower():
        company = company.title()

    return company


df["company"] = df["company"].apply(clean_company)

df[["company"]].head(10)

                                    company
0  Elsewedy Electric Power Systems Projects
1                                Elevenlabs
2                    Greenfix Property Care
3                        Saudi Aramco (ASC)
4                              Lucid Motors
5                                    Seerah
6                                 Ennismore
7                                Hill Intl.
8                         PrimeGate Company
9                                Euro Group

In [53]:
def extract_experience_level(title, description):

    title = "" if pd.isna(title) else str(title).lower()
    description = "" if pd.isna(description) else str(description).lower()

    # 1. Check job title
    if re.search(r"\bintern(ship)?\b", title):
        return "Intern"

    if re.search(r"\bsenior\s+lead\b", title):
        return "Senior Lead"

    if re.search(r"\bprincipal\b", title):
        return "Principal"

    if re.search(r"\b(?:senior|sr\.?)\b", title):
        return "Senior"

    if re.search(r"\b(?:lead|team lead|leader)\b", title):
        return "Lead"

    if re.search(r"\b(?:manager|manger)\b", title):
        return "Manager"

    if re.search(r"\bdirector\b", title):
        return "Director"

    if re.search(r"\b(?:junior|jr\.?|entry[- ]level)\b", title):
        return "Junior"

    # 2. Check years of experience in description
    match = re.search(
        r"\b(\d+)\s*(?:-|to)\s*(\d+)\s*years?",
        description
    )

    if match:
        years = int(match.group(1))

        if years <= 2:
            return "Junior"
        elif years <= 5:
            return "Mid Level"
        else:
            return "Senior"

    # Example: 5+ years
    match = re.search(
        r"\b(\d+)\s*\+\s*years?",
        description
    )

    if match:
        years = int(match.group(1))

        if years <= 2:
            return "Junior"
        elif years <= 5:
            return "Mid Level"
        else:
            return "Senior"

    # Example: at least 3 years / minimum 5 years
    match = re.search(
        r"\b(?:minimum|at least)\s+(\d+)\s*years?",
        description
    )

    if match:
        years = int(match.group(1))

        if years <= 2:
            return "Junior"
        elif years <= 5:
            return "Mid Level"
        else:
            return "Senior"

    # Example: 3 years of experience
    match = re.search(
        r"\b(\d+)\s*years?\s+(?:of\s+)?experience\b",
        description
    )

    if match:
        years = int(match.group(1))

        if years <= 2:
            return "Junior"
        elif years <= 5:
            return "Mid Level"
        else:
            return "Senior"

    return pd.NA


# Count missing values before
missing_before = df["experience_level"].isna().sum()

# Only transform rows where experience_level is missing
mask = df["experience_level"].isna()

df.loc[mask, "experience_level"] = df.loc[mask].apply(
    lambda row: extract_experience_level(
        row["job_title"],
        row["description"]
    ),
    axis=1
)

# Count missing values after
missing_after = df["experience_level"].isna().sum()

print("Missing before:", missing_before)
print("Missing after:", missing_after)
print("Recovered:", missing_before - missing_after)

print("\nExperience levels:")
print(df["experience_level"].value_counts(dropna=False))

Missing before: 50
Missing after: 22
Recovered: 28

Experience levels:
experience_level
<NA>           22
Senior         19
Lead           14
Manager         5
Junior          3
Mid Level       3
Intern          2
Principal       1
Senior Lead     1
Name: count, dtype: Int64

In [54]:
missing_before = df["experience_level"].isna().sum()

mask = df["experience_level"].isna()

df.loc[mask, "experience_level"] = df.loc[mask].apply(
    lambda row: extract_experience_level(
        row["job_title"],
        row["description"]
    ),
    axis=1
)

# Convert unsuccessful extraction back to missing
df["experience_level"] = df["experience_level"].replace(
    "N/A",
    pd.NA
)

missing_after = df["experience_level"].isna().sum()

print("Missing experience levels before:", missing_before)
print("Missing experience levels after:", missing_after)
print("Experience levels recovered:", missing_before - missing_after)

print("\nExperience level distribution:")
print(df["experience_level"].value_counts(dropna=False))

Missing experience levels before: 22
Missing experience levels after: 22
Experience levels recovered: 0

Experience level distribution:
experience_level
<NA>           22
Senior         19
Lead           14
Manager         5
Junior          3
Mid Level       3
Intern          2
Principal       1
Senior Lead     1
Name: count, dtype: Int64

In [55]:
def clean_skills(value):
    if pd.isna(value):
        return pd.NA

    skills = [
        skill.strip()
        for skill in str(value).split(",")
        if skill.strip()
    ]

    # Remove duplicate skills while keeping order
    skills = list(dict.fromkeys(skills))

    return ", ".join(skills) if skills else pd.NA


df["final_skills"] = df["final_skills"].apply(clean_skills)

df[["job_title", "final_skills"]].head(10)

,job_title,final_skills
0,"Senior Mechanical Quality Assurance Engineer, KSA",Quality Assurance
1,Forward Deployed Engineer - Software Engineer ...,"Python, Software Development, AI"
2,Quality Engineer,Automation Testing
3,Deal Quality Specialist,NaN
4,Incoming Quality Sr. Supervisor,NaN
5,Quality Engineer,"Quality Assurance, Quality Control, Compliance..."
6,Quality Manager,"Quality Assurance, Compliance"
7,PMO Operations & Quality Lead,"Quality Assurance, Monitoring"
8,Software Engineer,Web Applications
9,Software Developer & Database Architects,Database

In [56]:
print("===== FINAL DATA QUALITY REPORT =====")

print("\nRows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing values:")
print(
    df.isna()
      .sum()
      .sort_values(ascending=False)
)

print("\nData types:")
print(df.dtypes)

print("\nDuplicate jobs:")
print(
    df.duplicated(
        subset=["job_title", "company", "location"]
    ).sum()
)

===== FINAL DATA QUALITY REPORT =====

Rows: 70
Columns: 22

Missing values:
salary              70
city                54
skills              49
employment_type     45
final_skills        42
combined_text       40
listed_skills       40
extracted_skills    40
experience_level    22
posted_date         15
posted_month        15
posted_day          15
posted_year         15
posted_at           15
description         14
company              0
source               0
job_title            0
location             0
apply_link           0
has_salary           0
is_remote            0
dtype: int64

Data types:
source                           string
job_title                        string
company                             str
city                                str
location                         string
employment_type                  string
salary                          Float64
skills                              str
experience_level                 string
apply_link                          str
posted_at           datetime64[ns, UTC]
description                         str
combined_text                       str
extracted_skills                 object
listed_skills                    object
final_skills                        str
is_remote                       boolean
has_salary                      boolean
posted_date                      object
posted_year                       Int64
posted_month                      Int64
posted_day                        Int64
dtype: object

Duplicate jobs:
0

In [57]:
from pathlib import Path

output_dir = Path("../data")
output_dir.mkdir(exist_ok=True)

output_file = output_dir / "jobs_cleaned.json"

df.to_json(
    output_file,
    orient="records",
    force_ascii=False,
    indent=2,
    date_format="iso"
)

print("Data saved successfully!")
print("Rows saved:", len(df))
print("Saved to:", output_file.resolve())

Data saved successfully!
Rows saved: 70
Saved to: /Users/renadabdullah/JopDataPipeline123/data/jobs_cleaned.json

In [58]:
from pathlib import Path

wrong_file = Path("data/jobs_cleaned.json")

if wrong_file.exists():
    wrong_file.unlink()
    print("Deleted:", wrong_file.resolve())
else:
    print("File not found:", wrong_file.resolve())

File not found: /Users/renadabdullah/JopDataPipeline123/df/data/jobs_cleaned.json

In [59]:
from pathlib import Path

wrong_file = Path("jobs_cleaned.json")

if wrong_file.exists():
    wrong_file.unlink()
    print("Deleted:", wrong_file.resolve())
else:
    print("File not found")

File not found