In [1]:
import json
import pandas as pd

with open("../data/jobs_results_enriched.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)

print(df.shape)
df.head()

(30, 15)

,source,job_title,company,city,location,employment_type,salary,skills,experience_level,apply_link,posted_at,description,combined_text,extracted_skills,final_skills
0,Jooble,"Senior Mechanical Quality Assurance Engineer, KSA",elsewedy electric power systems projects,N/A,Saudi Arabia,N/A,,Quality Assurance,Senior,https://sa.jooble.org/jdp/6257477343626522564,2026-09-11T17:07:27.2500000,&nbsp;...elsewedy electric power systems proje...,"Senior Mechanical Quality Assurance Engineer, ...",[Quality Assurance],Quality Assurance
1,Jooble,Forward Deployed Engineer - Software Engineer ...,elevenlabs,N/A,Saudi Arabia,N/A,,Python,N/A,https://sa.jooble.org/jdp/7464896514165086194,2026-09-11T11:55:39.4447750+00:00,&nbsp;...beneath you. \r\n AI first: We use A...,Forward Deployed Engineer - Software Engineer ...,[Python],Python
2,Jooble,Quality Engineer,Greenfix Property Care,N/A,Saudi Arabia,N/A,,N/A,Junior,https://sa.jooble.org/jdp/-2119268642614167659,2025-12-07T03:15:41.8570000,Overview We are seeking a <b>Software </b>Te...,Quality Engineer Overview We are seeking a <...,[Automation Testing],Automation Testing
3,Jooble,Deal Quality Specialist,Saudi Aramco (ASC),N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/3549816380665494847,2026-01-12T00:00:00.0000000,"&nbsp;...companies in the world, as well as am...",Deal Quality Specialist &nbsp;...companies in ...,[],N/A
4,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,N/A,Saudi Arabia,N/A,,N/A,Senior,https://sa.jooble.org/jdp/-1483870771996984571,2026-08-07T11:23:21.9900000,&nbsp;...the world forward. Built on Lucid’s p...,Incoming Quality Sr. Supervisor &nbsp;...the w...,[],N/A

In [2]:
print(df.columns.tolist())
print(df.dtypes)
df.isnull().sum()

['source', 'job_title', 'company', 'city', 'location', 'employment_type', 'salary', 'skills', 'experience_level', 'apply_link', 'posted_at', 'description', 'combined_text', 'extracted_skills', 'final_skills']
source                 str
job_title              str
company                str
city                   str
location               str
employment_type        str
salary                 str
skills                 str
experience_level       str
apply_link             str
posted_at              str
description            str
combined_text          str
extracted_skills    object
final_skills           str
dtype: object

source              0
job_title           0
company             0
city                0
location            0
employment_type     0
salary              0
skills              0
experience_level    0
apply_link          0
posted_at           0
description         0
combined_text       0
extracted_skills    0
final_skills        0
dtype: int64

In [4]:
import json
import pandas as pd

with open("../data/all_jobs_from_db.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)

print(df.shape)
df.head()

(56, 14)

,id,source,job_title,company,city,location,employment_type,salary,skills,experience_level,apply_link,posted_at,fetched_at,description
0,1,Jooble,Quality Engineer,Greenfix Property Care,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/-2119268642614167659,2025-12-07T03:15:41.8570000,2026-09-06 18:40:21,NaN
1,2,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/-1483870771996984571,2026-08-07T11:23:21.9900000,2026-09-06 18:40:21,NaN
2,3,Jooble,Quality Engineer,Seerah,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/8180032376905932691,2026-09-03T00:00:00.0000000,2026-09-06 18:40:21,NaN
3,4,Jooble,Quality Manager,Ennismore,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/-4060408321821370081,2026-09-05T00:00:00.0000000,2026-09-06 18:40:21,NaN
4,5,Jooble,Software Engineer,PrimeGate Company,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/-2685678295966072847,2026-09-05T00:00:00.0000000,2026-09-06 18:40:21,NaN

In [9]:
import json
import pandas as pd

with open("../data/jobs_master.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.json_normalize(data)

print(df.shape)
df.head(10)

(56, 16)

,source,job_title,company,city,location,employment_type,salary,skills,experience_level,apply_link,posted_at,description,combined_text,extracted_skills,listed_skills,final_skills
0,Jooble,"Senior Mechanical Quality Assurance Engineer, KSA",elsewedy electric power systems projects,N/A,Saudi Arabia,N/A,,Quality Assurance,Senior,https://sa.jooble.org/jdp/6257477343626522564,2026-09-11T17:07:27.2500000,&nbsp;...elsewedy electric power systems proje...,"Senior Mechanical Quality Assurance Engineer, ...",[Quality Assurance],[],Quality Assurance
1,Jooble,Forward Deployed Engineer - Software Engineer ...,elevenlabs,N/A,Saudi Arabia,N/A,,Python,N/A,https://sa.jooble.org/jdp/7464896514165086194,2026-09-11T11:55:39.4447750+00:00,&nbsp;...beneath you. \r\n AI first: We use A...,Forward Deployed Engineer - Software Engineer ...,"[Python, Software Development, AI]",[],"Python, Software Development, AI"
2,Jooble,Quality Engineer,Greenfix Property Care,N/A,Saudi Arabia,N/A,,N/A,Junior,https://sa.jooble.org/jdp/-2119268642614167659,2025-12-07T03:15:41.8570000,Overview We are seeking a <b>Software </b>Te...,Quality Engineer Overview We are seeking a <...,[Automation Testing],[],Automation Testing
3,Jooble,Deal Quality Specialist,Saudi Aramco (ASC),N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/3549816380665494847,2026-01-12T00:00:00.0000000,"&nbsp;...companies in the world, as well as am...",Deal Quality Specialist &nbsp;...companies in ...,[],[],N/A
4,Jooble,Incoming Quality Sr. Supervisor,Lucid Motors,N/A,Saudi Arabia,N/A,,N/A,Senior,https://sa.jooble.org/jdp/-1483870771996984571,2026-08-07T11:23:21.9900000,&nbsp;...the world forward. Built on Lucid’s p...,Incoming Quality Sr. Supervisor &nbsp;...the w...,[],[],N/A
5,Jooble,Quality Engineer,Seerah,N/A,Saudi Arabia,N/A,,QA,N/A,https://sa.jooble.org/jdp/8180032376905932691,2026-09-08T00:00:00.0000000,&nbsp;...Job Description: \r\n Seerah is seeki...,Quality Engineer &nbsp;...Job Description: \r\...,"[Quality Assurance, Quality Control, Complianc...",[],"Quality Assurance, Quality Control, Compliance..."
6,Jooble,Quality Manager,Ennismore,N/A,Saudi Arabia,N/A,,N/A,Manager,https://sa.jooble.org/jdp/-4060408321821370081,2026-09-10T00:00:00.0000000,&nbsp;...you to help bring this vision to life...,Quality Manager &nbsp;...you to help bring thi...,"[Quality Assurance, Compliance]",[],"Quality Assurance, Compliance"
7,Jooble,PMO Operations & Quality Lead,Hill Intl.,N/A,Saudi Arabia,N/A,,Quality Assurance,Lead,https://sa.jooble.org/jdp/6732476449698777483,2026-09-11T00:00:00.0000000,&nbsp;...Manager (E1) to lead PMO best practic...,PMO Operations & Quality Lead &nbsp;...Manager...,"[Monitoring, Quality Assurance]",[],"Quality Assurance, Monitoring"
8,Jooble,Software Engineer,PrimeGate Company,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/-2685678295966072847,2026-09-10T00:00:00.0000000,&nbsp;...About the Role \r\n We are looking fo...,Software Engineer &nbsp;...About the Role \r\n...,[Web Applications],[],Web Applications
9,Jooble,Software Developer & Database Architects,Euro Group,N/A,Saudi Arabia,N/A,,N/A,N/A,https://sa.jooble.org/jdp/-1459070999588527884,2026-09-07T00:00:00.0000000,&nbsp;...<b>Software </b>Developer & Database ...,Software Developer & Database Architects &nbsp...,[Database],[],Database

In [10]:
print(df.columns.tolist())
print(df.dtypes)
df.isnull().sum()

['source', 'job_title', 'company', 'city', 'location', 'employment_type', 'salary', 'skills', 'experience_level', 'apply_link', 'posted_at', 'description', 'combined_text', 'extracted_skills', 'listed_skills', 'final_skills']
source                 str
job_title              str
company                str
city                   str
location               str
employment_type        str
salary                 str
skills                 str
experience_level       str
apply_link             str
posted_at              str
description            str
combined_text          str
extracted_skills    object
listed_skills       object
final_skills           str
dtype: object

source               0
job_title            0
company              0
city                 0
location             0
employment_type      0
salary               0
skills               0
experience_level     0
apply_link           0
posted_at           10
description         14
combined_text       26
extracted_skills    26
listed_skills       26
final_skills        26
dtype: int64